import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import { AdminLayout } from "@/components/layout/AdminLayout";
import NextTopLoader from "nextjs-toploader";


const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  display: "swap",
  preload: true,
  variable: "--font-ubuntu",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${ubuntu.variable} antialiased`} lang="en">
      <body
        className={`${ubuntu.className}  `}
      >
        <NextTopLoader color="#B6F500" easing="ease" showSpinner={false} />

        <AdminLayout>
          {children}
        </AdminLayout>
      </body>
    </html>
  );
}
